title: g33kidd
description: My Personal blog
author: Joshua Kidd
github: https://github.com/g33kidd
about: Hi! My name is Josh. Primarily I use Ruby on Rails and Node, but I'm always learning things. Recently have enjoyed Crystal, Elixir, and Dart. For front-end I use VueJS and ReactJS.
disqus_shortname: g33kidd
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/g33kidd"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/g33kidd"
    - icon: fa-github
      link: "https://github.com/g33kidd"
    - icon: fa-twitch
      link: "https://twitch.tv/g33kidd"

share:
  twitter_username: g33kidd
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "http://g33kidd.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
